"""Single source of truth for the unified table, the method lineage graph, the feedback-space map and
the timeline. Every entry is transcribed from a method card in the chapters (which are sourced in
research-log.md); edit the card and this file together.

Fields
------
name, short     display names (short is used in figures)
chapter         chapter file where the method card lives
family          policy_gradient | preference | imitation | calibration | classical
year            year of the primary source
parent          the method this one modifies (lineage edge), or None
changed         what changed vs the parent, in a few words
signal, q, w, stability, credit, models, targets, lineage   the method-card fields
feedback        0 = instructive (labels/demonstrations) ... 1 = evaluative (rewards); 0.5 = preferences
data            0 = fixed dataset (offline), 0.5 = slightly off-policy / iterated, 1 = fully on-policy
"""

M = [
    dict(name="REINFORCE", short="REINFORCE", chapter="02-policy-gradients", family="classical", year=1992, parent=None,
         changed="(root) score-function gradient", signal="scalar reward", q=r"$\pi_\theta$ (on-policy)", w=r"$r$ or $r-b$",
         stability="small learning rate", credit="sequence (reward-to-go per step in MDPs)", models="policy",
         targets=r"$\max\mathbb{E}[r]$ (no KL)", lineage="Williams 1992", feedback=1.0, data=1.0),
    dict(name="SFT (behavior cloning)", short="SFT", chapter="04-the-llm-as-a-policy", family="imitation", year=None, parent=None,
         changed="(root) maximum likelihood on demonstrations", signal="demonstrations", q="the dataset", w="1",
         stability="none needed", credit="token (teacher forcing)", models="policy", targets=r"forward KL to the data",
         lineage="behavior cloning; DAgger's problem case", feedback=0.0, data=0.0),
    dict(name="PPO (classical)", short="PPO", chapter="03-keeping-updates-stable", family="classical", year=2017, parent="REINFORCE",
         changed="clipped trust region, critic + GAE, minibatch reuse", signal="environment reward per step",
         q=r"$\pi_{\text{old}}$, reused for $K$ epochs", w=r"$\rho_t\hat A_t$, zeroed where the clip binds",
         stability=r"ratio clip; entropy bonus; optional KL to $\pi_{\text{old}}$", credit="per step (GAE)", models="policy, critic",
         targets="expected return", lineage="TRPO; actor-critic", feedback=1.0, data=0.85),
    dict(name="PPO-RLHF", short="PPO-RLHF", chapter="06-the-shared-target", family="policy_gradient", year=2022, parent="PPO (classical)",
         changed=r"learned reward model; per-token KL to a fixed $\pi_{\text{ref}}$ in the reward",
         signal=r"reward model at the end, $-\beta\log(\pi/\pi_{\text{ref}})$ per token", q=r"$\pi_{\text{old}}$ (fresh rollouts, few epochs)",
         w=r"$\rho_t\hat A_t$ (GAE), clipped", stability=r"KL to $\pi_{\text{ref}}$ in the reward; clip", credit="token (critic + GAE)",
         models="policy, reference, reward model, critic", targets=r"$\pi^\star$ of the learned reward", lineage="PPO actor-critic on the token MDP",
         feedback=1.0, data=0.85),
    dict(name="RLOO", short="RLOO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2024, parent="REINFORCE",
         changed="leave-one-out baseline from G samples; no critic", signal="scalar reward (KL folded in)", q=r"$\pi_\theta$, $G$ per prompt",
         w=r"$r_i - \mathrm{mean}_{j\ne i} r_j$", stability="KL-shaped reward", credit="sequence", models="policy, reference, reward",
         targets=r"$\pi^\star$", lineage="REINFORCE + Monte Carlo baseline (Kool et al. 2019)", feedback=1.0, data=1.0),
    dict(name="ReMax", short="ReMax", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2023, parent="REINFORCE",
         changed="greedy-response reward as baseline", signal="scalar reward", q=r"$\pi_\theta$ + one greedy decode",
         w=r"$r(y) - r(\bar y_{\text{greedy}})$", stability=r"KL to $\pi_{\text{ref}}$ in the reward", credit="sequence",
         models="policy, reference, reward", targets=r"$\pi^\star$", lineage="self-critical sequence training", feedback=1.0, data=1.0),
    dict(name="GRPO", short="GRPO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2024, parent="PPO-RLHF",
         changed=r"critic replaced by group mean/std; KL moved to the loss ($k_3$)", signal="scalar reward (often verifiable)",
         q=r"$\pi_{\text{old}}$, $G$ per prompt", w=r"$(r_i-\bar r)/\mathrm{std}$, clipped ratio, $1/\lvert o_i\rvert$",
         stability=r"clip; $k_3$ KL in the loss", credit="sequence advantage on every token", models="policy, reference",
         targets=r"approx. $\pi^\star$ (forward-KL regularizer)", lineage="REINFORCE + MC baseline + PPO trust region", feedback=1.0, data=0.85),
    dict(name="Dr. GRPO", short="Dr. GRPO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2025, parent="GRPO",
         changed=r"removes the std and $1/\lvert o_i\rvert$ normalizations", signal="scalar reward", q=r"$\pi_{\text{old}}$, $G$ per prompt",
         w=r"$r_i - \bar r$, clipped ratio, constant normalizer", stability="clip", credit="sequence", models="policy (+ reference)",
         targets="reward objective without length/difficulty reweighting", lineage="REINFORCE + MC baseline + clip", feedback=1.0, data=0.85),
    dict(name="DAPO", short="DAPO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2025, parent="GRPO",
         changed="clip-higher, dynamic sampling, token-level loss, overlong shaping, no KL", signal="verifiable reward + overlong shaping",
         q=r"$\pi_{\text{old}}$, groups with non-zero variance only", w=r"group-normalized advantage, $\epsilon_{\text{high}}>\epsilon_{\text{low}}$, token-level sum",
         stability="asymmetric clip; no KL", credit="sequence advantage, token aggregation", models="policy",
         targets="reward objective (no KL anchor)", lineage="REINFORCE + MC baseline + asymmetric trust region", feedback=1.0, data=0.85),
    dict(name="GSPO", short="GSPO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2025, parent="GRPO",
         changed="sequence-level importance ratio and clip", signal="scalar reward", q=r"$\pi_{\text{old}}$, $G$ per prompt",
         w=r"group-normalized advantage, clipped $s_i(\theta)$", stability="sequence-level clip", credit="sequence throughout",
         models="policy (+ reference)", targets="reward objective, sequence-level trust region", lineage="importance-sampled PG on the whole action",
         feedback=1.0, data=0.85),
    dict(name="CISPO", short="CISPO", chapter="08-policy-gradients-without-a-critic", family="policy_gradient", year=2025, parent="GRPO",
         changed="clips the importance weight, never drops token gradients", signal="scalar reward", q=r"$\pi_{\text{old}}$",
         w=r"$\mathrm{sg}(\mathrm{clip}(\rho_t))\hat A$", stability="clipped IS weight; token-level aggregation",
         credit="sequence advantage, token weights", models="policy (+ reference)", targets="reward objective",
         lineage="truncated importance sampling (IMPALA's V-trace)", feedback=1.0, data=0.85),
    dict(name="DPO", short="DPO", chapter="07-direct-preference-methods", family="preference", year=2023, parent="PPO-RLHF",
         changed=r"closed form inverted: reward expressed through $\pi$; no RM, no sampling", signal="pairwise preferences",
         q="fixed dataset of pairs", w=r"$\pm\beta\sigma(\hat r^- - \hat r^+)$", stability=r"log-ratio to $\pi_{\text{ref}}$ in the loss",
         credit="sequence", models="policy, reference", targets=r"$\pi^\star$ (infinite full-support data)", lineage="none in RL: Bradley-Terry logistic regression",
         feedback=0.5, data=0.0),
    dict(name="Online DPO", short="online DPO", chapter="07-direct-preference-methods", family="preference", year=2024, parent="DPO",
         changed="pairs sampled from the current policy and labelled on the fly", signal="pairwise preferences (online annotator)",
         q=r"$\pi_\theta$ (pairs)", w=r"$\pm\beta\sigma(\hat r^- - \hat r^+)$", stability=r"log-ratio to $\pi_{\text{ref}}$",
         credit="sequence", models="policy, reference, annotator", targets=r"$\pi^\star$", lineage="DPO's loss with RL's data regime", feedback=0.5, data=1.0),
    dict(name="IPO", short="IPO", chapter="07-direct-preference-methods", family="preference", year=2023, parent="DPO",
         changed="bounded (identity) preference transform: squared loss to a fixed target", signal="pairwise preferences",
         q="fixed dataset of pairs", w=r"$\pm 2(\frac{1}{2\tau} - h_\theta)$", stability="bounded target", credit="sequence",
         models="policy, reference", targets=r"$\pi_{\text{ref}}$ tilted by preference probability", lineage="none in RL: least squares",
         feedback=0.5, data=0.0),
    dict(name="KTO", short="KTO", chapter="07-direct-preference-methods", family="preference", year=2024, parent="DPO",
         changed="unpaired binary desirable/undesirable labels; reference point", signal="binary labels on single responses",
         q="fixed dataset", w=r"$\pm\lambda\beta\sigma'(\cdot)$ around $z_0$", stability=r"log-ratio to $\pi_{\text{ref}}$; $z_0$",
         credit="sequence", models="policy, reference", targets="prospect-theoretic utility of the implicit reward", lineage="none in RL: prospect theory",
         feedback=0.5, data=0.0),
    dict(name="SimPO", short="SimPO", chapter="07-direct-preference-methods", family="preference", year=2024, parent="DPO",
         changed="reference-free, length-normalized reward, target margin", signal="pairwise preferences", q="fixed dataset of pairs",
         w=r"$\pm\frac{\beta}{\lvert y\rvert}\sigma(-\text{margin})$", stability=r"margin $\gamma$; no KL", credit="sequence, length-normalized",
         models="policy", targets=r"no $\pi^\star$ (no reference)", lineage="none in RL: margin logistic loss", feedback=0.5, data=0.0),
    dict(name="ORPO", short="ORPO", chapter="07-direct-preference-methods", family="preference", year=2024, parent="DPO",
         changed="SFT + odds-ratio preference term; no reference; single stage", signal="preferences + preferred responses",
         q="fixed dataset", w=r"$+1$ (SFT) plus signed odds-ratio weight", stability="SFT term; no KL", credit="sequence",
         models="policy", targets="SFT objective with a preference penalty", lineage="behavior cloning + pairwise loss", feedback=0.3, data=0.0),
    dict(name="Best-of-n", short="best-of-n", chapter="09-imitating-a-better-distribution", family="imitation", year=None, parent=None,
         changed="(inference-time) pick the highest-scoring of n samples", signal="reward model or verifier", q=r"$\pi_{\text{ref}}$, $n$ samples",
         w="1 on the argmax, 0 otherwise", stability="none (no training)", credit="sequence", models="policy, reward",
         targets=r"a distribution just below the $\pi^\star_\beta$ frontier", lineage="rejection / order-statistic sampling", feedback=1.0, data=0.0),
    dict(name="Rejection-sampling FT / STaR / ReST / RAFT", short="RFT / STaR / ReST", chapter="09-imitating-a-better-distribution", family="imitation",
         year=2022, parent="SFT (behavior cloning)", changed="SFT on the policy's own filtered samples, iterated",
         signal="reward used as a filter", q=r"$\pi_{\text{ref}}$ or the current policy", w=r"$\mathbb{1}[\text{good}]$ (or $e^{r/\beta}$)",
         stability="none needed (supervised)", credit="sequence", models="policy (+ filter)",
         targets=r"$\pi^\star$ with exact acceptance; sharper (collapsing) when iterated with hard filters",
         lineage="reward-weighted regression; expert iteration", feedback=1.0, data=0.5),
    dict(name="Off-policy distillation", short="off-policy distill.", chapter="09-imitating-a-better-distribution", family="imitation", year=2016,
         parent="SFT (behavior cloning)", changed="demonstrations come from a teacher model", signal="teacher samples", q=r"the teacher $\pi_T$",
         w="1", stability="none needed", credit="token (teacher forcing)", models="student (+ teacher to sample)",
         targets=r"forward KL to the teacher", lineage="behavior cloning of the teacher", feedback=0.0, data=0.0),
    dict(name="On-policy distillation / GKD", short="on-policy distill.", chapter="09-imitating-a-better-distribution", family="imitation", year=2023,
         parent="Off-policy distillation", changed="student samples, teacher scores every token (dense reward)",
         signal="teacher per-token log-probs", q=r"the student $\pi_\theta$", w=r"$-(\log\pi_\theta - \log\pi_T)$ per token",
         stability="dense signal", credit="token", models="student, teacher", targets="the teacher (reverse KL)",
         lineage="DAgger; PG with a dense shaped reward", feedback=0.2, data=1.0),
    dict(name="Correctness + proper scoring rule (book's reconstruction)", short="calibration reward", chapter="10-rewarding-calibration",
         family="calibration", year=2025, parent="REINFORCE", changed="reward scores the stated confidence with a proper scoring rule",
         signal=r"$\mathbb{1}[\text{correct}] - (p - \mathbb{1}[\text{correct}])^2$", q=r"$\pi_\theta$, several per prompt",
         w="reward minus leave-one-out baseline", stability="small learning rate (KL optional)", credit="one decision (contextual bandit)",
         models="policy (+ verifier)", targets="best answer + honest probability", lineage="REINFORCE in a contextual bandit; forecasting scoring rules",
         feedback=1.0, data=1.0),
    dict(name="RLCD (TypeSafe AI)", short="RLCD (TypeSafe)", chapter="10-rewarding-calibration", family="calibration", year=2026,
         parent=None, changed="undisclosed", signal="calibrated decisions (objective public; reward undisclosed)", q="undisclosed",
         w="undisclosed", stability="undisclosed", credit="undisclosed", models="undisclosed",
         targets="calibrated probabilities over typed answers (stated goal)", lineage="undisclosed", feedback=1.0, data=None),
]

FIELDS = ["signal", "q", "w", "stability", "credit", "models", "targets", "lineage", "changed"]
HEADERS = {"signal": "Signal", "q": "Samples from ($q$)", "w": "Per-sample weight ($w$)", "stability": "Stability",
           "credit": "Credit granularity", "models": "Models in memory", "targets": "Targets",
           "lineage": "Classical lineage", "changed": "What changed vs its parent"}

# Dated milestones for the timeline appendix. Every year is the year of the primary source as
# recorded in research-log.md (arXiv submission year unless a venue year is the usual citation).
TIMELINE = [
    (1992, "REINFORCE (Williams)", "classical"),
    (2007, "reward-weighted regression", "classical"),
    (2011, "DAgger", "imitation"),
    (2015, "TRPO; GAE", "classical"),
    (2016, "sequence-level KD; REINFORCE for text (MIXER)", "imitation"),
    (2017, "PPO; RL from human preferences; KL-control", "classical"),
    (2019, "RLHF on language models (Ziegler et al.); AWR", "policy_gradient"),
    (2020, "learning to summarize from feedback", "policy_gradient"),
    (2022, "InstructGPT; Constitutional AI / RLAIF; STaR", "policy_gradient"),
    (2022, "KL-regularized RL as inference; RM overoptimization", "classical"),
    (2023, "DPO; IPO", "preference"),
    (2023, "RAFT; ReST; ReMax; GKD; process supervision", "imitation"),
    (2024, "KTO; ORPO; SimPO; online DPO", "preference"),
    (2024, "RLOO for RLHF; GRPO; RLVR (Tülu 3)", "policy_gradient"),
    (2025, "DeepSeek-R1; Dr. GRPO; DAPO; GSPO; CISPO", "policy_gradient"),
    (2025, "on-policy distillation (Thinking Machines)", "imitation"),
    (2025, "RLCR; behaviorally calibrated RL", "calibration"),
    (2026, "RLCD (TypeSafe AI, mechanism undisclosed)", "calibration"),
]
